//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Richard
    {
        public int ID { get; set; }
        public string PLANT_LOC_ID { get; set; }
        public string APPLICATION_CD { get; set; }
        public string PNL_SZ_NUM { get; set; }
        public string ITEM_ID { get; set; }
        public string MODEL_NAME { get; set; }
        public string DATA_CATG_CD { get; set; }
        public string DATA_TYPE_CD { get; set; }
        public string TIGER_IND { get; set; }
        public string CLNDR_MN { get; set; }
        public string UOM_CD { get; set; }
        public string BEG_INV_QTY { get; set; }
        public string CMPY_NAME { get; set; }
    }

    public class RootObject
    {
        public List<Richard> excel { get; set; }
    }
}
